<a href="https://colab.research.google.com/github/kondimidi/data-science-boot/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)  
>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)  
>
>Podstawowa biblioteka do obliczeń numerycznych w języku Python.
>
>Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:
```
pip install numpy
```

### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe operacje na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)
7. [Indeksowanie, Wycinanie](#a7)
8. [Iteracja po tablicach](#a8)
9. [Zmiana rozmiaru tablic](#a9)
10. [Maski logiczne](#a10)


### <a name='a1'></a> Podstawy

In [1]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [12]:
x = np.array([1, 3])
print(type(x))
print("wymiar:",x.ndim)
print("ksztalt:",x.shape)
print("rozmiar:",x.size)
print("typ danych:", x.dtype)
print(x)
x

<class 'numpy.ndarray'>
wymiar: 1
ksztalt: (2,)
rozmiar: 2
typ danych: int64
[1 3]


array([1, 3])

*2D* Array

In [14]:
x = np.array([[1, 3],[-3,1]])
print(type(x))
print("wymiar:",x.ndim)
print("ksztalt:",x.shape)
print("rozmiar:",x.size)
x

<class 'numpy.ndarray'>
wymiar: 2
ksztalt: (2, 2)
rozmiar: 4


array([[ 1,  3],
       [-3,  1]])

3D Array

In [15]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]],

     [[3, 2, 1],
      [4, 3, 2]]]
)
print("wymiar:",x.ndim)
print("ksztalt:",x.shape)
print("rozmiar:",x.size)
x

wymiar: 3
ksztalt: (3, 2, 3)
rozmiar: 18


array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

### <a name='a2'></a> Typy danych

In [33]:
A = np.array([1, 2])
print(A.dtype)
A = np.array([1.2, 2.3])
print(A.dtype)
A = np.array([1, 2], dtype="float")
print(A.dtype)
A = np.array([1.2, 2.3], dtype="complex")
print(A.dtype)
A = np.array([1.2, 2.3], dtype="int")
print(A.dtype)
A = np.array([False, True])
print(A.dtype)
A = np.array([120, 124], dtype=np.int8)
print(A.dtype)
A = np.array([25, 64], dtype=np.uint8)
print(A.dtype)

int64
float64
float64
complex128
int64
bool
int8
uint8


### <a name='a3'></a> Tworzenie tablic

In [48]:
np.zeros(shape=(4, 10))
np.zeros(shape=(4, 10), dtype='int')
np.ones(shape=(5, 5))
np.ones(shape=(5, 5), dtype="int")
np.full(shape=(3, 3), fill_value=4, dtype='int')
np.arange(10)
np.arange(start=5, stop=10)
np.arange(start=10, stop=100, step=10)
np.arange(start=100, stop=10, step=-10)
np.arange(start=0, stop=1, step=0.05)
np.linspace(start=0, stop=1, num=11) # w liniowy sposob tworzy zbiór liczb od podanego zakresu

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [49]:
A = np.arange(15)
print(A.reshape((3, 5)),"\n")
print(A.reshape((3, -1)),"\n")
print(A.reshape((-1, 3)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


### <a name='a4'></a> Podstawowe operacje na tablicach

In [52]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [57]:
print(A + B) # np.add(A, B)
print(A - B) # np.subtract(A, B)
print(A * B) # np.multiply(A, B)
print(A / B) # np.divide(A, B)
print(A + 3)
print(2 * B)
print(A + 3*B)

[6 0 7 4]
[0 2 1 0]
[ 9 -1 12  4]
[ 1.         -1.          1.33333333  1.        ]
[6 4 7 5]
[ 6 -2  6  4]
[12 -2 13  8]


In [63]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, "\n")
print(Y, "\n")
print(X * Y, "\n")
print(np.dot(X, Y), "\n") # X.dot(Y) or X @ Y
print(np.dot(Y, X)) # Y.dot(X)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]] 

[[6 0]
 [2 0]] 

[[  3   6]
 [-12   0]] 

[[ 6 18]
 [-5 -3]]


### <a name='a5'></a>  Generowanie liczb pseudolosowych

In [ ]:
np.random.seed(0)

In [66]:
print(np.random.randn(), "\n")
print(np.random.randn(10), "\n")
print(np.random.randn(10, 4), "\n")
print(np.random.rand(), "\n")
print(np.random.rand(10), "\n")
print(np.random.rand(10, 2), "\n")
print(np.random.randint(10), "\n")
print(np.random.randint(low=10, high=101), "\n")
print(np.random.choice([4, 2, 1, 3, 5]), "\n")
print(np.random.choice(['python', 'java', 'sql']), "\n")

0.20242608729688663 

[ 0.31933301 -1.3523424   0.27772306  0.18457457 -1.25469921 -0.7565587
 -0.46741331 -0.5551765  -1.55985259  0.15361791] 

[[ 1.38999749 -0.13195934  1.41822049  0.48982838]
 [ 0.70456266 -1.013125   -1.79857314  1.00164624]
 [ 0.81232609 -1.35449545 -0.14770036 -0.59341733]
 [-0.82645807  0.484556    0.86270852 -2.27351586]
 [ 0.50633727 -0.58689872 -0.9192248   0.09789822]
 [-2.55922531 -0.13132399  1.6884582   0.802529  ]
 [-0.1493873  -0.24722497  1.13533209 -0.94737592]
 [ 0.22643549  0.72515379 -0.78113307  0.09203348]
 [-0.71391544 -1.27026775  1.613501    0.04607295]
 [-0.70865191  0.22839476  0.01061698 -0.92811844]] 

0.31179841962895294 

[0.29546647 0.35605627 0.85436384 0.47893749 0.48208261 0.38340387
 0.37477046 0.255377   0.62375088 0.16597864] 

[[0.82664658 0.23974977]
 [0.18467558 0.31954432]
 [0.0474108  0.39043457]
 [0.88562442 0.08161563]
 [0.80193953 0.2171431 ]
 [0.65718949 0.58370206]
 [0.83727654 0.60428042]
 [0.06531287 0.44205321]
 [0.

In [69]:
data = np.arange(10)
print(data, "\n")
np.random.shuffle(data)
data

[0 1 2 3 4 5 6 7 8 9] 



array([6, 1, 9, 7, 2, 0, 3, 4, 5, 8])

### <a name='a6'></a> Podstawowe funkcje

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.sqrt(9)

3.0

In [ ]:
np.all([2, 3, 1])

False

In [ ]:
np.any([0, 0, 0])

False

In [ ]:
bool(1.3)

True

In [ ]:
A = np.random.rand(5)
A

array([0.58127287, 0.88173536, 0.69253159, 0.72525428, 0.50132438])

In [ ]:
np.argmax(A)

1

In [ ]:
A[np.argmax(A)]

0.8817353618548528

In [ ]:
np.argmin(A)

4

In [ ]:
np.argsort(A)

array([4, 0, 2, 3, 1])

In [ ]:
np.max(A)

0.8817353618548528

In [ ]:
np.min(A)

0.5013243819267023

In [ ]:
np.mean(A)

0.676423697262964

In [ ]:
np.median(A)

0.6925315900777659

In [ ]:
np.std(A)

0.13000786074672221

###  <a name='a7'></a> Indeksowanie, Wycinanie

In [ ]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [ ]:
A[2]

2

In [ ]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
A[:2]

array([0, 1])

In [ ]:
A[[0, 2]]

array([0, 2])

In [ ]:
A[-1]

19

In [ ]:
A[10:15]

array([10, 11, 12, 13, 14])

In [ ]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### <a name='a8'></a> Iteracja po tablicach

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
for row in A:
    print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
for row in A:
    print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [ ]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


### <a name='a9'></a> Zmiana rozmiaru tablic

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A.shape

(4, 5)

In [ ]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### <a name='a10'></a> Maski logiczne

In [ ]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [ ]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [ ]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])